
asm("	.section	.rodata\n");
asm("	.align	2\n");
asm(".LC0:\n");
asm("	.ascii	\" File cannot be opened \" \n");
asm("	.align	2\n");
asm(".LC1:\n");
asm("	.ascii	\"% 127 s\" \n");
asm("	.text\n");
asm("	.align	2\n");
asm("	.global	main\n");
asm("	.syntax unified\n");
asm("	.arm\n");
asm("	.fpu softvfp\n");
asm("	.type	main, %function\n");
asm("main:\n");
asm("	@ args = 0, pretend = 0, frame = 144\n");
asm("	@ frame_needed = 1, uses_anonymous_args = 0\n");
asm("	push	{fp, lr}\n");
asm("	add	fp, sp, #4\n");
asm("	sub	sp, sp, #144\n");
asm("	str	r0, [fp, #-144]\n");
asm("	str	r1, [fp, #-148]\n");
asm("	ldr	r3, [fp, #-148]\n");
asm("	add	r3, r3, #4\n");
asm("	ldr	r3, [r3]\n");
asm("	mov	r1, #65\n");
asm("	mov	r0, r3\n");
asm("	bl	open(PLT)\n");
asm("	str	r0, [fp, #-8]\n");
asm("	ldr	r3, [fp, #-8]\n");
asm("	cmn	r3, #1\n");
asm("	bne	.L2\n");
asm("	ldr	r3, .L5\n");
asm(".LPIC0:\n");
asm("	add	r3, pc, r3\n");
asm("	mov	r0, r3\n");
asm("	bl	perror(PLT)\n");
asm("	mov	r3, #1\n");
asm("	b	.L4\n");
asm(".L2:\n");
asm("	sub	r3, fp, #136\n");
asm("	mov	r1, r3\n");
asm("	ldr	r3, .L5+4\n");
asm(".LPIC1:\n");
asm("	add	r3, pc, r3\n");
asm("	mov	r0, r3\n");
asm("	bl	scanf(PLT)\n");
asm("	sub	r3, fp, #136\n");
asm("	mov	r0, r3\n");
asm("	bl	strlen(PLT)\n");
asm("	mov	r2, r0\n");
asm("	sub	r3, fp, #136\n");
asm("	mov	r1, r3\n");
asm("	ldr	r0, [fp, #-8]\n");
asm("	bl	write(PLT)\n");
asm("	ldr	r0, [fp, #-8]\n");
asm("	bl	close(PLT)\n");
asm("	mov	r3, #0\n");
asm(".L4:\n");
asm("	mov	r0, r3\n");
asm("	sub	sp, fp, #4\n");
asm("	@ sp needed\n");
asm("	pop	{fp, pc}\n");
asm(".L6:\n");
asm("	.align	2\n");
asm(".L5:\n");
asm("	.word	.LC0-(.LPIC0+8)\n");
asm("	.word	.LC1-(.LPIC1+8)\n");
asm("	.size	main, .-main\n");
